@extends('layouts.app')

@section('content')
    @include('components.page-header', ['title' => 'Customer Satisfaction', 'subtitle' => 'Monitor feedback and ratings'])
    <div class="card p-3"><form method="GET" action="{{ route('support.customer-satisfaction') }}"><div class="row g-3"><div class="col-md-7"><label class="form-label small text-muted">Search</label><input name="search" class="form-control form-control-sm" value="{{ $search ?? '' }}" placeholder="Ticket number, customer, or comments..." /></div><div class="col-md-3"><label class="form-label small text-muted">Rating</label><select name="rating" class="form-select form-select-sm"><option value="all">All Ratings</option>@foreach([5 => 'Very Satisfied', 4 => 'Satisfied', 3 => 'Neutral', 2 => 'Dissatisfied', 1 => 'Very Dissatisfied'] as $ratingOption => $label)<option value="{{ $ratingOption }}" @selected((string) ($rating ?? '') === (string) $ratingOption)>{{ $ratingOption }} - {{ $label }}</option>@endforeach</select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-sm w-100" style="background:#5347CE;color:#fff;">Apply</button></div></div></form></div>
    <div class="row g-3 my-1"><div class="col-md-3"><div class="card p-3"><div class="text-muted small">Total Responses</div><div class="fw-bold fs-5">{{ $responsesCount }}</div></div></div><div class="col-md-3"><div class="card p-3"><div class="text-muted small">Average Rating</div><div class="fw-bold fs-5">{{ $averageRating }} / 5</div></div></div><div class="col-md-3"><div class="card p-3"><div class="text-muted small">Satisfied Responses</div><div class="fw-bold fs-5">{{ $satisfactionPct }}%</div><div class="text-muted small">Ratings 4–5</div></div></div><div class="col-md-3"><div class="card p-3"><div class="text-muted small">Dissatisfied Responses</div><div class="fw-bold fs-5">{{ $dissatisfiedCount }}</div><div class="text-muted small">Ratings 1–2</div></div></div></div>
    <div class="card p-4 mt-4"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Feedback</th><th>Ticket</th><th>Customer</th><th>Rating</th><th>Satisfaction Level</th><th>Comments</th><th>Submitted</th></tr></thead><tbody>@forelse($satisfactions as $feedback)<tr><td class="fw-semibold">FB-{{ $feedback->feedback_id }}</td><td><a class="text-decoration-none fw-bold" style="color:#5347CE" href="{{ route('support.tickets', ['ticket_id' => $feedback->ticket_id]) }}">TK-{{ $feedback->ticket_id }}</a></td><td>{{ $feedback->supportTicket?->customer?->full_name ?? '—' }}</td><td>{{ $feedback->rating ?? '—' }}</td><td>{{ $feedback->satisfaction_level ?? '—' }}</td><td>{{ $feedback->comments ?? '—' }}</td><td>{{ $feedback->submitted_at?->format('Y-m-d H:i') ?? '—' }}</td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No satisfaction feedback found.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $satisfactions->links('pagination::bootstrap-5') }}</div></div>
    <div class="card p-3 mt-4"><div class="text-muted small mb-2">Rating Distribution</div><div class="d-flex gap-2 flex-wrap">@foreach([5, 4, 3, 2, 1] as $ratingOption)<span class="badge bg-secondary">{{ $ratingOption }} stars: {{ $ratingDistribution[$ratingOption] ?? 0 }}</span>@endforeach</div></div>
@endsection
