@extends('layouts.app')

@section('content')
    <style>
        .satisfaction-dashboard { --cs-primary:#5347CE; --cs-surface:#fff; --cs-border:#e9eaf1; --cs-muted:#697386; --cs-text:#1f2937; }
        .satisfaction-dashboard .cs-filter-card, .satisfaction-dashboard .cs-table-card, .satisfaction-dashboard .cs-chart-card, .satisfaction-dashboard .cs-kpi { background:var(--cs-surface); border:1px solid var(--cs-border); border-radius:16px; box-shadow:0 8px 22px rgba(31,41,55,.055); }
        .satisfaction-dashboard .cs-kpi { height:100%; padding:1.25rem; position:relative; overflow:hidden; }
        .satisfaction-dashboard .cs-kpi::after { content:''; position:absolute; width:100px; height:100px; border-radius:50%; right:-34px; top:-38px; background:var(--cs-kpi-soft); }
        .satisfaction-dashboard .cs-kpi-icon { width:42px; height:42px; border-radius:12px; display:inline-flex; align-items:center; justify-content:center; color:var(--cs-kpi-color); background:var(--cs-kpi-soft); font-size:1.2rem; }
        .satisfaction-dashboard .cs-kpi-label { color:var(--cs-muted); font-size:.76rem; font-weight:600; letter-spacing:.02em; text-transform:uppercase; }
        .satisfaction-dashboard .cs-kpi-value { color:var(--cs-text); font-size:1.7rem; font-weight:700; letter-spacing:-.04em; line-height:1.15; }
        .satisfaction-dashboard .cs-kpi-note { color:var(--cs-muted); font-size:.78rem; }
        .satisfaction-dashboard .cs-filter-card { padding:1.25rem 1.5rem; }
        .satisfaction-dashboard .cs-filter-grid { align-items:end; display:grid; gap:1rem; grid-template-columns:minmax(250px,2fr) minmax(150px,.9fr) minmax(150px,.8fr) auto; padding:.15rem .35rem; }
        .satisfaction-dashboard .cs-filter-actions { display:flex; gap:.75rem; justify-self:end; }
        .satisfaction-dashboard .cs-filter-label { color:var(--cs-muted); font-size:.75rem; font-weight:600; margin-bottom:.4rem; }
        .satisfaction-dashboard .cs-filter-card .form-control, .satisfaction-dashboard .cs-filter-card .form-select { border-color:#dfe1ea; min-height:38px; font-size:.86rem; }
        .satisfaction-dashboard .cs-filter-card .form-control:focus, .satisfaction-dashboard .cs-filter-card .form-select:focus { border-color:var(--cs-primary); box-shadow:0 0 0 .2rem rgba(83,71,206,.12); }
        .satisfaction-dashboard .cs-apply, .satisfaction-dashboard .cs-reset { align-items:center; display:inline-flex; justify-content:center; min-height:38px; padding-inline:1rem; font-size:.86rem; font-weight:600; white-space:nowrap; }
        .satisfaction-dashboard .cs-apply { background:var(--cs-primary); border-color:var(--cs-primary); box-shadow:0 6px 14px rgba(83,71,206,.22); }
        .satisfaction-dashboard .cs-apply:hover, .satisfaction-dashboard .cs-apply:focus { background:#4338ca; border-color:#4338ca; }
        .satisfaction-dashboard .cs-reset { border-color:#d7dae5; color:#4b5563; }.satisfaction-dashboard .cs-reset:hover, .satisfaction-dashboard .cs-reset:focus { background:#f7f7fb; border-color:#c8ccda; color:#374151; }
        .satisfaction-dashboard .cs-table-card { overflow:hidden; }
        .satisfaction-dashboard .cs-table-heading { padding:1.25rem 1.25rem .75rem; }
        .satisfaction-dashboard .cs-table-heading h2 { color:var(--cs-text); font-size:1rem; font-weight:700; margin:0; }
        .satisfaction-dashboard .cs-table-heading p { color:var(--cs-muted); font-size:.8rem; margin:.25rem 0 0; }
        .satisfaction-dashboard .cs-table { margin:0; min-width:1060px; }
        .satisfaction-dashboard .cs-table thead th { background:#f8f9fc; border-bottom:1px solid var(--cs-border); color:#697386; font-size:.7rem; font-weight:700; letter-spacing:.04em; padding:.85rem 1rem; text-transform:uppercase; white-space:nowrap; }
        .satisfaction-dashboard .cs-table tbody td { border-color:#f0f1f5; color:#374151; font-size:.84rem; padding:1rem; vertical-align:middle; }
        .satisfaction-dashboard .cs-table tbody tr { transition:background-color .16s ease, transform .16s ease; }
        .satisfaction-dashboard .cs-table tbody tr:hover { background:#fafaff; }
        .satisfaction-dashboard .cs-ticket-link { color:var(--cs-primary); font-weight:700; text-decoration:none; }
        .satisfaction-dashboard .cs-ticket-link:hover { color:#3f36a4; text-decoration:underline; }
        .satisfaction-dashboard .cs-comment { line-height:1.5; max-width:310px; min-width:210px; overflow-wrap:anywhere; white-space:normal; }
        .satisfaction-dashboard .cs-stars { color:#f59e0b; font-size:.84rem; letter-spacing:1px; white-space:nowrap; }
        .satisfaction-dashboard .cs-rating-number { color:#4b5563; font-size:.76rem; font-weight:700; margin-left:.3rem; }
        .satisfaction-dashboard .cs-badge { border-radius:999px; display:inline-flex; align-items:center; font-size:.7rem; font-weight:700; line-height:1.1; padding:.38rem .62rem; white-space:nowrap; }
        .satisfaction-dashboard .cs-level-very-satisfied { background:#dcfce7; color:#166534; }.satisfaction-dashboard .cs-level-satisfied { background:#dbeafe; color:#1d4ed8; }.satisfaction-dashboard .cs-level-neutral { background:#e5e7eb; color:#4b5563; }.satisfaction-dashboard .cs-level-dissatisfied { background:#ffedd5; color:#c2410c; }.satisfaction-dashboard .cs-level-very-dissatisfied { background:#fee2e2; color:#b91c1c; }
        .satisfaction-dashboard .cs-status-received { background:#dcfce7; color:#166534; }.satisfaction-dashboard .cs-status-pending { background:#fef3c7; color:#92400e; }
        .satisfaction-dashboard .cs-awaiting { color:#9ca3af; font-size:.78rem; font-style:italic; white-space:nowrap; }
        .satisfaction-dashboard .cs-chart-card { padding:1.25rem; height:100%; }
        .satisfaction-dashboard .cs-chart-title { color:var(--cs-text); font-size:.95rem; font-weight:700; margin:0; }.satisfaction-dashboard .cs-chart-subtitle { color:var(--cs-muted); font-size:.76rem; margin:.22rem 0 1.1rem; }
        .satisfaction-dashboard .cs-chart-row { align-items:center; display:grid; gap:.7rem; grid-template-columns:100px 1fr 28px; margin-bottom:.82rem; }.satisfaction-dashboard .cs-chart-label { color:#4b5563; font-size:.78rem; }.satisfaction-dashboard .cs-chart-track { background:#eef0f6; border-radius:999px; height:10px; overflow:hidden; }.satisfaction-dashboard .cs-chart-bar { background:linear-gradient(90deg, #5347ce, #887cfd); border-radius:inherit; height:100%; min-width:0; }.satisfaction-dashboard .cs-chart-count { color:#4b5563; font-size:.78rem; font-weight:700; text-align:right; }
        .satisfaction-dashboard .cs-empty { color:var(--cs-muted); font-size:.88rem; padding:3rem 1rem!important; text-align:center; }
        @media (max-width: 991.98px) { .satisfaction-dashboard .cs-filter-grid { grid-template-columns:minmax(220px,1fr) minmax(180px,1fr); }.satisfaction-dashboard .cs-filter-actions { grid-column:1 / -1; justify-self:end; } }
        @media (max-width: 767.98px) { .satisfaction-dashboard .cs-kpi-value { font-size:1.5rem; }.satisfaction-dashboard .cs-filter-card { padding:1rem; }.satisfaction-dashboard .cs-filter-grid { grid-template-columns:1fr; padding:0; }.satisfaction-dashboard .cs-filter-actions { grid-column:auto; justify-self:stretch; }.satisfaction-dashboard .cs-filter-actions .btn { flex:1; }.satisfaction-dashboard .cs-table-heading { padding:1rem; }.satisfaction-dashboard .cs-chart-row { grid-template-columns:86px 1fr 24px; } }
    </style>

    <div class="satisfaction-dashboard">
        @include('components.page-header', ['title' => 'Customer Satisfaction', 'subtitle' => 'View and analyze customer-submitted feedback'])

        <section class="row g-3 mb-4" aria-label="Customer satisfaction summary">
            <div class="col-sm-6 col-xl-3"><article class="cs-kpi" style="--cs-kpi-color:#5347CE;--cs-kpi-soft:#eeecff;"><div class="d-flex justify-content-between align-items-start"><span class="cs-kpi-icon"><i class="bi bi-chat-square-text" aria-hidden="true"></i></span></div><div class="cs-kpi-value mt-3">{{ $responsesCount }}</div><div class="cs-kpi-label mt-1">Feedback Responses</div><div class="cs-kpi-note mt-2">Customer submissions received</div></article></div>
            <div class="col-sm-6 col-xl-3"><article class="cs-kpi" style="--cs-kpi-color:#d97706;--cs-kpi-soft:#fff7df;"><div class="d-flex justify-content-between align-items-start"><span class="cs-kpi-icon"><i class="bi bi-star-fill" aria-hidden="true"></i></span></div><div class="cs-kpi-value mt-3">{{ $averageRating }}<span class="fs-6 text-muted fw-semibold"> / 5</span></div><div class="cs-kpi-label mt-1">Average Rating</div><div class="cs-kpi-note mt-2">Across received feedback</div></article></div>
            <div class="col-sm-6 col-xl-3"><article class="cs-kpi" style="--cs-kpi-color:#15803d;--cs-kpi-soft:#e7f8ed;"><div class="d-flex justify-content-between align-items-start"><span class="cs-kpi-icon"><i class="bi bi-graph-up-arrow" aria-hidden="true"></i></span></div><div class="cs-kpi-value mt-3">{{ $satisfactionPct }}%</div><div class="cs-kpi-label mt-1">Satisfaction Score</div><div class="cs-kpi-note mt-2">Ratings of 4 or 5</div></article></div>
            <div class="col-sm-6 col-xl-3"><article class="cs-kpi" style="--cs-kpi-color:#dc2626;--cs-kpi-soft:#ffebeb;"><div class="d-flex justify-content-between align-items-start"><span class="cs-kpi-icon"><i class="bi bi-emoji-frown" aria-hidden="true"></i></span></div><div class="cs-kpi-value mt-3">{{ $dissatisfiedCount }}</div><div class="cs-kpi-label mt-1">Dissatisfied Responses</div><div class="cs-kpi-note mt-2">Ratings of 1 or 2</div></article></div>
        </section>

        <section class="cs-filter-card mb-4" aria-label="Feedback filters"><form method="GET" action="{{ route('support.customer-satisfaction') }}"><div class="cs-filter-grid"><div><label class="form-label cs-filter-label" for="satisfactionSearch">Search feedback</label><div class="input-group"><span class="input-group-text bg-white border-end-0"><i class="bi bi-search text-muted" aria-hidden="true"></i></span><input id="satisfactionSearch" name="search" class="form-control border-start-0 ps-0" value="{{ $search ?? '' }}" placeholder="Ticket, customer, or comment" /></div></div><div><label class="form-label cs-filter-label" for="satisfactionRating">Rating</label><select id="satisfactionRating" name="rating" class="form-select"><option value="all">All ratings</option>@foreach([5 => 'Very Satisfied', 4 => 'Satisfied', 3 => 'Neutral', 2 => 'Dissatisfied', 1 => 'Very Dissatisfied'] as $ratingOption => $label)<option value="{{ $ratingOption }}" @selected((string) ($rating ?? '') === (string) $ratingOption)>{{ $ratingOption }} - {{ $label }}</option>@endforeach</select></div><div><label class="form-label cs-filter-label" for="satisfactionSort">Sort by</label><select id="satisfactionSort" name="sort" class="form-select"><option value="newest" @selected($sort === 'newest')>Newest first</option><option value="oldest" @selected($sort === 'oldest')>Oldest first</option><option value="rating_desc" @selected($sort === 'rating_desc')>Highest rating</option><option value="rating_asc" @selected($sort === 'rating_asc')>Lowest rating</option></select></div><div class="cs-filter-actions"><a class="btn btn-outline-secondary cs-reset" data-support-reset="1" href="{{ route('support.customer-satisfaction') }}">Reset</a><button class="btn btn-primary cs-apply" type="submit"><i class="bi bi-funnel me-1" aria-hidden="true"></i>Apply</button></div></div></form></section>

        <section class="cs-table-card mb-4"><div class="cs-table-heading"><h2>Feedback Records</h2><p>Customer feedback is displayed as read-only information.</p></div><div class="table-responsive"><table class="table cs-table"><thead><tr><th>Feedback ID</th><th>Ticket</th><th>Customer</th><th>Rating</th><th>Satisfaction Level</th><th>Comments</th><th>Submitted Date</th><th>Status</th></tr></thead><tbody>@forelse($satisfactions as $feedback)<tr><td class="fw-semibold text-nowrap">FB-{{ $feedback->feedback_id }}</td><td><a class="cs-ticket-link" href="{{ route('support.tickets', ['ticket_id' => $feedback->ticket_id]) }}">TK-{{ $feedback->ticket_id }}</a></td><td class="fw-semibold">{{ $feedback->supportTicket?->customer?->full_name ?? '—' }}</td>@if($feedback->submitted_at)<td><span class="cs-stars" aria-label="{{ $feedback->rating }} out of 5 stars">@for($star = 1; $star <= 5; $star++)<i class="bi bi-star{{ $star <= $feedback->rating ? '-fill' : '' }}" aria-hidden="true"></i>@endfor</span><span class="cs-rating-number">{{ $feedback->rating }}/5</span></td>@php($levelClass = match($feedback->satisfaction_level) { 'Very Satisfied' => 'cs-level-very-satisfied', 'Satisfied' => 'cs-level-satisfied', 'Neutral' => 'cs-level-neutral', 'Dissatisfied' => 'cs-level-dissatisfied', default => 'cs-level-very-dissatisfied' })<td><span class="cs-badge {{ $levelClass }}">{{ $feedback->satisfaction_level }}</span></td><td class="cs-comment">{{ $feedback->comments ?: '—' }}</td><td class="text-nowrap">{{ $feedback->submitted_at->format('Y-m-d H:i') }}</td><td><span class="cs-badge cs-status-received"><i class="bi bi-check-circle-fill me-1" aria-hidden="true"></i>Received</span></td>@else<td colspan="4"><span class="cs-awaiting"><i class="bi bi-hourglass-split me-1" aria-hidden="true"></i>Awaiting Customer Feedback</span></td><td><span class="cs-badge cs-status-pending"><i class="bi bi-clock me-1" aria-hidden="true"></i>Pending Customer Feedback</span></td>@endif</tr>@empty<tr><td colspan="8" class="cs-empty"><i class="bi bi-inbox fs-4 d-block mb-2" aria-hidden="true"></i>No customer feedback found for the selected filters.</td></tr>@endforelse</tbody></table></div><x-support-pagination :paginator="$satisfactions" /></section>

        @php($ratingMaximum = max(1, ...array_values($ratingDistribution->all())))
        @php($levelMaximum = max(1, ...array_values($satisfactionLevelCounts->all())))
        <section class="row g-4 mb-2" aria-label="Feedback distributions"><div class="col-lg-6"><article class="cs-chart-card"><h2 class="cs-chart-title">Rating Distribution</h2><p class="cs-chart-subtitle">Breakdown of received ratings from 1 to 5 stars.</p>@foreach([5, 4, 3, 2, 1] as $ratingOption)@php($count = $ratingDistribution[$ratingOption] ?? 0)<div class="cs-chart-row"><span class="cs-chart-label">{{ $ratingOption }} star{{ $ratingOption === 1 ? '' : 's' }}</span><div class="cs-chart-track" role="progressbar" aria-label="{{ $ratingOption }} star ratings" aria-valuenow="{{ $count }}" aria-valuemin="0" aria-valuemax="{{ $ratingMaximum }}"><div class="cs-chart-bar" style="width:{{ ($count / $ratingMaximum) * 100 }}%"></div></div><span class="cs-chart-count">{{ $count }}</span></div>@endforeach</article></div><div class="col-lg-6"><article class="cs-chart-card"><h2 class="cs-chart-title">Satisfaction Levels</h2><p class="cs-chart-subtitle">Response count by customer-selected satisfaction level.</p>@foreach(['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied', 'Very Dissatisfied'] as $level)@php($count = $satisfactionLevelCounts[$level] ?? 0)<div class="cs-chart-row"><span class="cs-chart-label">{{ $level }}</span><div class="cs-chart-track" role="progressbar" aria-label="{{ $level }} responses" aria-valuenow="{{ $count }}" aria-valuemin="0" aria-valuemax="{{ $levelMaximum }}"><div class="cs-chart-bar" style="width:{{ ($count / $levelMaximum) * 100 }}%"></div></div><span class="cs-chart-count">{{ $count }}</span></div>@endforeach</article></div></section>
    </div>
@endsection
