<div class="d-flex justify-content-end mb-3"><button class="btn support-primary" type="button" data-bs-toggle="modal" data-bs-target="#supportCreateModal"><i class="bi bi-plus-lg me-1"></i> Add New</button></div>
@if(request()->routeIs('support.tickets'))
<div class="modal fade" id="supportCreateModal" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="POST" action="{{ route('support.tickets.store') }}">@csrf
<div class="modal-header"><h5 class="modal-title">Create Support Ticket</h5><button class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body"><div class="row g-3">
<div class="col-md-6"><label class="form-label">Sales Order</label><select class="form-select" name="order_id" required>@foreach($salesOrders as $order)<option value="{{ $order->order_id }}">{{ $order->order_number }} — {{ $order->customer?->full_name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Product</label><select class="form-select" name="product_id" required>@foreach($salesOrders->flatMap->items->pluck('product')->filter()->unique('product_id') as $product)<option value="{{ $product->product_id }}">{{ $product->product_name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Ticket Type</label><input class="form-control" name="ticket_type" required></div>
<div class="col-md-3"><label class="form-label">Priority</label><select class="form-select" name="priority"><option>High</option><option selected>Medium</option><option>Low</option></select></div>
<div class="col-md-3"><label class="form-label">Department Queue</label><select class="form-select" name="department"><option>After-Sales Support</option><option>Technical Support</option><option>Warranty</option><option>Field Service</option></select></div>
<div class="col-12"><label class="form-label">Subject</label><input class="form-control" name="subject" required></div>
<div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="4" required></textarea></div>
<div class="col-md-6"><label class="form-label">Service Contract (optional)</label><select class="form-select" name="service_contract_id"><option value="">None</option>@foreach($serviceContracts as $contract)<option value="{{ $contract->contract_id }}">{{ $contract->contract_number }}</option>@endforeach</select></div>
</div></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal" type="button">Cancel</button><button class="btn support-primary">Create Ticket</button></div></form></div></div>
@elseif(request()->routeIs('support.warranty-records'))
<div class="modal fade" id="supportCreateModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('support.warranty-records.store') }}">@csrf
<div class="modal-header"><h5 class="modal-title">Create Warranty Record</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-12"><label class="form-label">Sales Order</label><select class="form-select" name="order_id" required>@foreach($salesOrders as $order)<option value="{{ $order->order_id }}">{{ $order->order_number }} — {{ $order->customer?->full_name }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label">Product</label><select class="form-select" name="product_id" required>@foreach($products as $product)<option value="{{ $product->product_id }}">{{ $product->product_name }}</option>@endforeach</select></div>
<div class="col-6"><label class="form-label">Start</label><input class="form-control" type="date" name="warranty_start" value="{{ now()->toDateString() }}" required></div><div class="col-6"><label class="form-label">End</label><input class="form-control" type="date" name="warranty_end" required></div>
<div class="col-12"><label class="form-label">Status</label><select class="form-select" name="warranty_status"><option>Active</option><option>On Hold</option><option>Expired</option></select></div>
</div></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal" type="button">Cancel</button><button class="btn support-primary">Create Warranty</button></div></form></div></div>
@elseif(request()->routeIs('support.warranty-claims'))
<div class="modal fade" id="supportCreateModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('support.warranty-claims.store') }}">@csrf
<div class="modal-header"><h5 class="modal-title">Submit Warranty Claim</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-12"><label class="form-label">Warranty</label><select class="form-select" name="warranty_id" required>@foreach($warranties as $warranty)<option value="{{ $warranty->warranty_id }}">{{ $warranty->warranty_number }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label">Support Ticket</label><select class="form-select" name="ticket_id" required>@foreach($tickets as $ticket)<option value="{{ $ticket->ticket_id }}">TK-{{ $ticket->ticket_id }} — {{ $ticket->subject }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label">Claim Reason</label><textarea class="form-control" name="claim_reason" rows="4" required></textarea><div class="form-text">Coverage, order ownership, product match, and duplicates are checked automatically.</div></div>
</div></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal" type="button">Cancel</button><button class="btn support-primary">Submit Claim</button></div></form></div></div>
@elseif(request()->routeIs('support.service-contracts'))
<div class="modal fade" id="supportCreateModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('support.service-contracts.store') }}">@csrf
<div class="modal-header"><h5 class="modal-title">Create Service Contract</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-6"><label class="form-label">Customer</label><select class="form-select" name="customer_id" required>@foreach($customers as $customerOption)<option value="{{ $customerOption->customer_id }}">{{ $customerOption->full_name }}</option>@endforeach</select></div>
<div class="col-6"><label class="form-label">Product</label><select class="form-select" name="product_id" required>@foreach($products as $productOption)<option value="{{ $productOption->product_id }}">{{ $productOption->product_name }}</option>@endforeach</select></div>
<div class="col-8"><label class="form-label">Service Type</label><input class="form-control" name="service_type" required></div><div class="col-4"><label class="form-label">Service Limit</label><input class="form-control" type="number" min="1" name="service_limit"></div>
<div class="col-6"><label class="form-label">Start</label><input class="form-control" type="date" name="service_start" required></div><div class="col-6"><label class="form-label">End</label><input class="form-control" type="date" name="service_end" required></div>
<div class="col-12"><label class="form-label">Status</label><select class="form-select" name="contract_status"><option>Active</option><option>Suspended</option><option>Expired</option><option>Terminated</option></select></div>
</div></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal" type="button">Cancel</button><button class="btn support-primary">Create Contract</button></div></form></div></div>
@elseif(request()->routeIs('support.service-requests'))
<div class="modal fade" id="supportCreateModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('support.service-requests.store') }}">@csrf
<div class="modal-header"><h5 class="modal-title">Create Service Request</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-12"><label class="form-label">Support Ticket</label><select class="form-select" name="ticket_id" required>@foreach($tickets as $ticket)<option value="{{ $ticket->ticket_id }}">TK-{{ $ticket->ticket_id }} — {{ $ticket->subject }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label">Request Type</label><input class="form-control" name="request_type" required></div>
<div class="col-12"><label class="form-label">Preferred Technician</label><select class="form-select" name="technician_id"><option value="">Assign later</option>@foreach($technicians as $technicianOption)<option value="{{ $technicianOption->employee_id }}">{{ $technicianOption->full_name }} — {{ $technicianOption->department }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="schedule_notes"></textarea></div>
</div></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal" type="button">Cancel</button><button class="btn support-primary">Create Request</button></div></form></div></div>
@elseif(request()->routeIs('support.resolution-tracking'))
<div class="modal fade" id="supportCreateModal" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="POST" action="{{ route('support.resolution-tracking.store') }}">@csrf
<div class="modal-header"><h5 class="modal-title">Create Resolution Record</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-8"><label class="form-label">Ticket</label><select class="form-select" name="ticket_id" required>@foreach($tickets as $ticket)<option value="{{ $ticket->ticket_id }}">TK-{{ $ticket->ticket_id }} — {{ $ticket->subject }}</option>@endforeach</select></div>
<div class="col-4"><label class="form-label">Resolved By</label><select class="form-select" name="resolved_by" required>@foreach($employees as $employeeOption)<option value="{{ $employeeOption->employee_id }}">{{ $employeeOption->full_name }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label">Resolution Summary</label><textarea class="form-control" name="resolution_summary" required></textarea></div>
<div class="col-6"><label class="form-label">Root Cause</label><textarea class="form-control" name="root_cause" required></textarea></div><div class="col-6"><label class="form-label">Corrective Action</label><textarea class="form-control" name="corrective_action" required></textarea></div>
<div class="col-6"><label class="form-label">Time (hours)</label><input class="form-control" type="number" step=".25" min="0" name="resolution_time_hours" required></div><div class="col-6"><label class="form-label">QC Status</label><select class="form-select" name="qc_status"><option value="pending">Pending</option><option value="passed">Passed</option><option value="failed">Failed</option></select></div>
</div></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal" type="button">Cancel</button><button class="btn support-primary">Save Resolution</button></div></form></div></div>
@endif
