@extends('layouts.app')

@section('content')
    @include('components.page-header', ['title' => 'Resolution Tracking', 'subtitle' => 'Track resolutions and corrective actions'])
    @include('support.resolution-details-modal')
    <div class="card p-3"><form method="GET" action="{{ route('support.resolution-tracking') }}"><div class="row g-3"><div class="col-md-6"><label class="form-label small text-muted">Search</label><input name="search" class="form-control form-control-sm" value="{{ $search ?? '' }}" placeholder="Resolution, ticket, customer, employee..." /></div><div class="col-md-4"><label class="form-label small text-muted">Ticket Status</label><select class="form-select form-select-sm" name="ticket_status"><option value="all">All ticket statuses</option>@foreach(['Open', 'Pending', 'In Progress', 'Resolved', 'Closed', 'Escalated', 'Reopened'] as $statusOption)<option value="{{ $statusOption }}" @selected(($ticketStatus ?? '') === $statusOption)>{{ $statusOption }}</option>@endforeach</select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-sm w-100" style="background:#5347CE;color:#fff;">Apply</button></div></div></form></div>
    <div class="row g-3 my-1">@foreach([['Resolution Records', $totalResolutionCount], ['Resolved Tickets', $resolvedTicketCount], ['Avg. Resolution Time', $averageResolutionTime.'h'], ['QC Passed', $qcPassedCount], ['QC Failed', $qcFailedCount], ['Pending QC', $pendingQcCount]] as [$label, $value])<div class="col-md-4 col-lg-2"><div class="card p-3 h-100"><div class="text-muted small">{{ $label }}</div><div class="fw-bold fs-5">{{ $value }}</div></div></div>@endforeach</div>
    <div class="card p-4 mt-4"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Ticket</th><th>Resolved By</th><th>Root Cause</th><th>Corrective Action</th><th>Resolution Time</th><th>Resolved Date</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($resolutionTrackings as $resolution)<tr><td><a class="text-decoration-none fw-bold" style="color:#5347CE" href="{{ route('support.tickets', ['ticket_id' => $resolution->ticket_id]) }}">TK-{{ $resolution->ticket_id }}</a><div class="text-muted small">RS-{{ $resolution->resolution_id }}</div></td><td>{{ $resolution->employee?->full_name ?? $resolution->supportTicket?->latestAssignment?->employee?->full_name ?? '—' }}</td><td>{{ $resolution->root_cause ?? '—' }}</td><td>{{ $resolution->corrective_action ?? '—' }}</td><td>{{ $resolution->resolution_time_hours !== null ? $resolution->resolution_time_hours.'h' : '—' }}</td><td>{{ $resolution->resolved_at?->format('Y-m-d H:i') ?? '—' }}</td><td class="text-end"><button type="button" class="btn btn-sm btn-outline-primary js-resolution-view" data-resolution-id="{{ $resolution->resolution_id }}" data-bs-toggle="modal" data-bs-target="#resolutionDetailsModal"><i class="bi bi-eye me-1"></i>View</button></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No resolution records found.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $resolutionTrackings->links('pagination::bootstrap-5') }}</div></div>
    <script>(() => { const text = (id, value) => { const el = document.getElementById(id); if (el) el.textContent = value || '—'; }; document.querySelectorAll('.js-resolution-view').forEach((button) => button.addEventListener('click', async () => { try { const response = await fetch(`{{ url('/support/resolution-tracking') }}/${button.dataset.resolutionId}/show`, {headers: {'X-Requested-With': 'XMLHttpRequest'}}); if (!response.ok) throw new Error('Unable to load resolution details.'); const data = await response.json(); const modal = data.modal || {}; text('resolutionDetailsSubtitle', `RS-${data.resolution?.resolution_id || button.dataset.resolutionId}`); text('resolutionTicketNumberText', modal.resolutionTicketNumberText); text('resolutionResolvedByText', modal.resolutionResolvedByText); text('resolutionTimeHoursText', modal.resolutionTimeHoursText); text('resolutionResolvedDateText', modal.resolutionResolvedDateText); text('resolutionWorkflowStatusText', modal.resolutionWorkflowStatusText); text('resolutionRootCauseText', modal.resolutionRootCauseText); text('resolutionCorrectiveActionText', modal.resolutionCorrectiveActionText); const badge = document.getElementById('resolutionOutcomeBadge'); badge.textContent = modal.resolutionOutcomeBadge || '—'; badge.className = `badge ${modal.resolutionOutcomeBadge === 'Resolved' ? 'bg-success' : 'bg-primary'}`; } catch (error) { text('resolutionDetailsSubtitle', error.message); } })); })();</script>
@endsection
