@extends('layouts.app')

@section('content')
    <style>
        .resolution-dashboard { --rt-primary:#5347ce; --rt-border:#e8eaf0; --rt-muted:#6b7280; --rt-text:#1f2937; }
        .resolution-dashboard .rt-filter-card, .resolution-dashboard .rt-table-card, .resolution-dashboard .rt-kpi { background:#fff; border:1px solid var(--rt-border); border-radius:16px; box-shadow:0 8px 22px rgba(31,41,55,.055); }
        .resolution-dashboard .rt-filter-card { padding:1.25rem 1.5rem; }.resolution-dashboard .rt-filter-grid { align-items:end; display:grid; gap:1rem; grid-template-columns:minmax(260px,1.8fr) minmax(180px,.8fr) auto; padding:.15rem .35rem; }.resolution-dashboard .rt-filter-label { color:var(--rt-muted); font-size:.75rem; font-weight:600; margin-bottom:.4rem; }.resolution-dashboard .rt-filter-card .form-control, .resolution-dashboard .rt-filter-card .form-select { border-color:#dfe1ea; font-size:.86rem; min-height:38px; }.resolution-dashboard .rt-filter-card .form-control:focus, .resolution-dashboard .rt-filter-card .form-select:focus { border-color:var(--rt-primary); box-shadow:0 0 0 .2rem rgba(83,71,206,.12); }.resolution-dashboard .rt-filter-actions { display:flex; gap:.75rem; justify-self:end; }.resolution-dashboard .rt-apply, .resolution-dashboard .rt-reset { align-items:center; display:inline-flex; font-size:.86rem; font-weight:600; justify-content:center; min-height:38px; padding-inline:1rem; white-space:nowrap; }.resolution-dashboard .rt-apply { background:var(--rt-primary); border-color:var(--rt-primary); box-shadow:0 6px 14px rgba(83,71,206,.22); }.resolution-dashboard .rt-apply:hover, .resolution-dashboard .rt-apply:focus { background:#4338ca; border-color:#4338ca; }.resolution-dashboard .rt-reset { border-color:#d7dae5; color:#4b5563; }.resolution-dashboard .rt-reset:hover, .resolution-dashboard .rt-reset:focus { background:#f7f7fb; border-color:#c8ccda; color:#374151; }
        .resolution-dashboard .rt-kpi { height:100%; min-height:106px; padding:1.15rem; }.resolution-dashboard .rt-kpi-label { color:var(--rt-muted); font-size:.72rem; font-weight:700; letter-spacing:.03em; text-transform:uppercase; }.resolution-dashboard .rt-kpi-value { color:var(--rt-text); font-size:1.55rem; font-weight:700; letter-spacing:-.03em; margin-top:.45rem; }.resolution-dashboard .rt-kpi:nth-child(1) { border-top:3px solid #5347ce; }
        .resolution-dashboard .rt-table-card { margin-top:1.75rem; overflow:hidden; }.resolution-dashboard .rt-table-heading { padding:1.25rem 1.35rem .8rem; }.resolution-dashboard .rt-table-heading h2 { color:var(--rt-text); font-size:1rem; font-weight:700; margin:0; }.resolution-dashboard .rt-table-heading p { color:var(--rt-muted); font-size:.8rem; margin:.25rem 0 0; }.resolution-dashboard .rt-table { margin:0; min-width:1040px; }.resolution-dashboard .rt-table thead th { background:#f8f9fc; border-bottom:1px solid var(--rt-border); color:var(--rt-muted); font-size:.7rem; font-weight:700; letter-spacing:.04em; padding:.85rem 1rem; text-transform:uppercase; white-space:nowrap; }.resolution-dashboard .rt-table tbody td { border-color:#f0f1f5; color:#374151; font-size:.84rem; line-height:1.5; padding:1.1rem 1rem; vertical-align:middle; }.resolution-dashboard .rt-table tbody tr { transition:background-color .16s ease; }.resolution-dashboard .rt-table tbody tr:hover { background:#fafaff; }.resolution-dashboard .rt-ticket { color:var(--rt-primary); font-weight:700; text-decoration:none; }.resolution-dashboard .rt-ticket:hover { color:#3f36a4; text-decoration:underline; }.resolution-dashboard .rt-text-wrap { max-width:270px; min-width:190px; overflow-wrap:anywhere; }
        .resolution-dashboard .rt-action-header, .resolution-dashboard .rt-action-cell { min-width:164px; text-align:center; }.resolution-dashboard .rt-action-cell { padding-inline:1.1rem!important; }.resolution-dashboard .rt-action-stack { align-items:center; display:flex; flex-direction:column; gap:.65rem; justify-content:flex-start; min-height:78px; }.resolution-dashboard .rt-action-stack form { margin:0; width:128px; }.resolution-dashboard .rt-action-btn { align-items:center; border-radius:8px; display:inline-flex; font-size:.8rem; font-weight:600; height:34px; justify-content:center; padding:.4rem .7rem; transition:background-color .16s ease, border-color .16s ease, box-shadow .16s ease, transform .16s ease; width:128px; }.resolution-dashboard .rt-action-btn i { margin-right:.4rem; }.resolution-dashboard .rt-action-btn:hover { box-shadow:0 4px 10px rgba(31,41,55,.1); transform:translateY(-1px); }.resolution-dashboard .rt-action-btn:focus-visible { box-shadow:0 0 0 .2rem rgba(83,71,206,.2); outline:0; }.resolution-dashboard .rt-view-btn:hover { background:#eef2ff; border-color:#7c73df; color:#4338ca; }.resolution-dashboard .rt-approve-btn:hover { background:#ecfdf3; border-color:#4ade80; color:#15803d; }
        @media (max-width: 991.98px) { .resolution-dashboard .rt-filter-grid { grid-template-columns:minmax(220px,1fr) minmax(180px,1fr); }.resolution-dashboard .rt-filter-actions { grid-column:1 / -1; justify-self:end; } }
        @media (max-width: 767.98px) { .resolution-dashboard .rt-filter-card { padding:1rem; }.resolution-dashboard .rt-filter-grid { grid-template-columns:1fr; padding:0; }.resolution-dashboard .rt-filter-actions { grid-column:auto; justify-self:stretch; }.resolution-dashboard .rt-filter-actions .btn { flex:1; }.resolution-dashboard .rt-table-heading { padding:1rem; } }
    </style>

    <div class="resolution-dashboard">
        @include('components.page-header', ['title' => 'Resolution Tracking', 'subtitle' => 'Track resolutions and corrective actions'])
        @include('support.resolution-details-modal')

        <section class="rt-filter-card"><form method="GET" action="{{ route('support.resolution-tracking') }}"><div class="rt-filter-grid"><div><label class="form-label rt-filter-label" for="resolutionSearch">Search</label><div class="input-group"><span class="input-group-text bg-white border-end-0"><i class="bi bi-search text-muted" aria-hidden="true"></i></span><input id="resolutionSearch" name="search" class="form-control border-start-0 ps-0" value="{{ $search ?? '' }}" placeholder="Resolution, ticket, customer, employee..." /></div></div><div><label class="form-label rt-filter-label" for="resolutionStatus">Resolution Status</label><select id="resolutionStatus" class="form-select" name="resolution_status"><option value="all">All Statuses</option>@foreach($resolutionStatuses as $statusOption)<option value="{{ $statusOption }}" @selected(($resolutionStatus ?? '') === $statusOption)>{{ $statusOption }}</option>@endforeach</select></div><div class="rt-filter-actions"><a class="btn btn-outline-secondary rt-reset" data-support-reset="1" href="{{ route('support.resolution-tracking') }}">Reset</a><button class="btn btn-primary rt-apply" type="submit"><i class="bi bi-funnel me-1" aria-hidden="true"></i>Apply</button></div></div></form></section>

        <section class="row g-3 mt-2 mb-1" aria-label="Resolution summary">@foreach([['Resolution Records', $totalResolutionCount], ['Resolved Tickets', $resolvedTicketCount], ['Avg. Resolution Time', $averageResolutionTime.'h'], ['QC Passed', $qcPassedCount], ['QC Failed', $qcFailedCount], ['Pending QC', $pendingQcCount]] as [$label, $value])<div class="col-sm-6 col-lg-4 col-xxl-2"><article class="rt-kpi"><div class="rt-kpi-label">{{ $label }}</div><div class="rt-kpi-value">{{ $value }}</div></article></div>@endforeach</section>

        <section class="rt-table-card"><div class="rt-table-heading"><h2>Resolution Records</h2><p>Review resolution details or approve completed records.</p></div><div class="table-responsive"><table class="table rt-table"><thead><tr><th>Ticket</th><th>Resolved By</th><th>Root Cause</th><th>Corrective Action</th><th>Resolution Time</th><th>Resolved Date</th><th class="rt-action-header">Action</th></tr></thead><tbody>@forelse($resolutionTrackings as $resolution)<tr><td><a class="rt-ticket" href="{{ route('support.tickets', ['ticket_id' => $resolution->ticket_id]) }}">TK-{{ $resolution->ticket_id }}</a><div class="text-muted small mt-1">RS-{{ $resolution->resolution_id }} · {{ $resolution->resolution_status }}</div></td><td>{{ $resolution->employee?->full_name ?? $resolution->supportTicket?->latestAssignment?->employee?->full_name ?? '—' }}</td><td class="rt-text-wrap">{{ $resolution->root_cause ?? '—' }}</td><td class="rt-text-wrap">{{ $resolution->corrective_action ?? '—' }}</td><td class="text-nowrap">{{ $resolution->resolution_time_hours !== null ? $resolution->resolution_time_hours.'h' : '—' }}</td><td class="text-nowrap">{{ $resolution->resolved_at?->format('Y-m-d H:i') ?? '—' }}</td><td class="rt-action-cell"><div class="rt-action-stack"><button type="button" class="btn btn-outline-primary rt-action-btn rt-view-btn js-resolution-view" data-resolution-id="{{ $resolution->resolution_id }}" data-bs-toggle="modal" data-bs-target="#resolutionDetailsModal"><i class="bi bi-eye" aria-hidden="true"></i>View</button>@if($resolution->resolution_status!=='Approved')<form method="POST" action="{{ route('support.resolution-tracking.approve', $resolution) }}">@csrf @method('PATCH')<button class="btn btn-outline-success rt-action-btn rt-approve-btn" type="submit"><i class="bi bi-check2-circle" aria-hidden="true"></i>Approve</button></form>@endif</div></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-5">No resolution records found.</td></tr>@endforelse</tbody></table></div><x-support-pagination :paginator="$resolutionTrackings" /></section>
    </div>

    <script>(() => { const text = (id, value) => { const el = document.getElementById(id); if (el) el.textContent = value || '—'; }; document.querySelectorAll('.js-resolution-view').forEach((button) => button.addEventListener('click', async () => { try { const response = await fetch(`{{ url('/support/resolution-tracking') }}/${button.dataset.resolutionId}/show`, {headers: {'X-Requested-With': 'XMLHttpRequest'}}); if (!response.ok) throw new Error('Unable to load resolution details.'); const data = await response.json(); const modal = data.modal || {}; text('resolutionDetailsSubtitle', `RS-${data.resolution?.resolution_id || button.dataset.resolutionId}`); text('resolutionTicketNumberText', modal.resolutionTicketNumberText); text('resolutionResolvedByText', modal.resolutionResolvedByText); text('resolutionTimeHoursText', modal.resolutionTimeHoursText); text('resolutionResolvedDateText', modal.resolutionResolvedDateText); text('resolutionWorkflowStatusText', modal.resolutionWorkflowStatusText); text('resolutionRootCauseText', modal.resolutionRootCauseText); text('resolutionCorrectiveActionText', modal.resolutionCorrectiveActionText); const badge = document.getElementById('resolutionOutcomeBadge'); badge.textContent = modal.resolutionOutcomeBadge || '—'; badge.className = `badge ${modal.resolutionOutcomeBadge === 'Resolved' ? 'bg-success' : 'bg-primary'}`; } catch (error) { text('resolutionDetailsSubtitle', error.message); } })); })();</script>
@endsection
