@extends('layouts.app')

@section('content')
    @php
        $kpis = [
            ['label' => 'Total Revenue', 'value' => '₱'.number_format($dashboardKpis['totalRevenue']), 'icon' => 'cash-stack', 'tone' => 'text-success', 'accent' => 'rgba(16,185,129,.14)'],
            ['label' => 'Total Sales Target', 'value' => '₱'.number_format($dashboardKpis['salesTarget']), 'icon' => 'bullseye', 'tone' => 'text-primary', 'accent' => 'rgba(83,71,206,.12)'],
            ['label' => 'Target Achievement', 'value' => number_format($dashboardKpis['achievementRate']).'%', 'icon' => 'speedometer2', 'tone' => 'text-success', 'accent' => 'rgba(16,185,129,.14)'],
            ['label' => 'Revenue Growth', 'value' => '+'.number_format($dashboardKpis['revenueGrowth'], 1).'%', 'icon' => 'graph-up-arrow', 'tone' => 'text-success', 'accent' => 'rgba(18,139,153,.12)'],
            ['label' => 'Next-Month Forecast', 'value' => '₱'.number_format($dashboardKpis['nextMonthForecast']), 'icon' => 'calendar2-week', 'tone' => 'text-info', 'accent' => 'rgba(72,150,254,.14)'],
            ['label' => 'High-Priority Actions', 'value' => $dashboardKpis['highPriorityRecommendations'], 'icon' => 'exclamation-octagon', 'tone' => 'text-danger', 'accent' => 'rgba(239,68,68,.12)'],
        ];
        $modules = [
            ['title' => 'Sales Reports', 'route' => 'forecasting.reports', 'icon' => 'bar-chart-line', 'tone' => 'primary', 'description' => 'Analyze revenue trends and sales by product, region, and representative.', 'metrics' => [['Latest revenue','₱980,000'],['Top product','Product A'],['Top region','NCR'],['Top representative','Thervin']], 'action' => 'View Sales Reports'],
            ['title' => 'Target vs. Actual', 'route' => 'forecasting.performance', 'icon' => 'clipboard-data', 'tone' => 'success', 'description' => 'Compare planned targets with actual results and identify performance gaps.', 'metrics' => [['Achievement','103%'],['Sales gap','+₱295,000'],['Best performer','Thervin'],['Lowest performer','Peter Parker']], 'action' => 'View Performance'],
            ['title' => 'Forecasting', 'route' => 'forecasting.forecast', 'icon' => 'graph-up', 'tone' => 'info', 'description' => 'Review historical sales trends and predicted future revenue.', 'metrics' => [['Next month','₱1,040,000'],['Growth','+6.1%'],['Direction','Upward'],['Confidence','87%']], 'action' => 'View Forecast'],
            ['title' => 'Recommendations', 'route' => 'forecasting.recommendations', 'icon' => 'lightbulb', 'tone' => 'warning', 'description' => 'Review data-supported actions for sales, marketing, and inventory planning.', 'metrics' => [['Total actions','12'],['High priority','4'],['Opportunity','Product A'],['Main risk','Bicol']], 'action' => 'View Recommendations'],
        ];
    @endphp

    <main class="w-full flex items-center" style="margin:-1rem -1rem 0;width:calc(100% + 2rem);padding:32px 48px;height:258px;max-height:258px;background:linear-gradient(90deg,#128B99 0%,#1CE5BD 100%);border-radius:0;"><div class="d-flex flex-column h-100 w-100"><h1 class="text-white font-semibold text-[42px] leading-tight">Sales Performance Reporting and Forecasting</h1><div class="flex-grow-1 d-flex align-items-center"><p class="text-white mb-0" style="font-family:'Poppins',sans-serif;font-size:18px;font-weight:600;line-height:1.6;opacity:.95;">Monitor sales results, compare targets with actual performance, review future revenue forecasts, and identify recommended business actions.</p></div><div class="d-flex flex-wrap gap-2"><a href="{{ route('forecasting.reports') }}" class="hero-action-btn" style="padding:.75rem 1.6rem;">View Sales Reports</a><a href="{{ route('forecasting.forecast') }}" class="hero-secondary-btn"><i class="bi bi-graph-up-arrow me-2" aria-hidden="true"></i>View Forecast</a></div></div></main>

    <section class="mt-4" aria-label="Executive KPI summary"><div class="row g-4">@foreach($kpis as $kpi)<div class="col-12 col-md-6 col-lg-4"><article class="card border-0 shadow-sm h-100 px-3 py-2" style="background:linear-gradient(145deg,#fff,#f8fafc);min-height:92px;"><div class="d-flex justify-content-between align-items-center mb-1"><span class="small fw-semibold text-muted">{{ $kpi['label'] }}</span><span class="rounded-circle d-flex align-items-center justify-content-center" style="width:32px;height:32px;background:{{ $kpi['accent'] }}"><i class="bi bi-{{ $kpi['icon'] }} {{ $kpi['tone'] }}"></i></span></div><div class="fs-4 fw-bold {{ $kpi['tone'] }}">{{ $kpi['value'] }}</div><p class="small text-muted mb-0 mt-1">Executive overview</p></article></div>@endforeach</div></section>

    <section class="mt-5" aria-labelledby="module-navigation-heading"><h2 id="module-navigation-heading" class="text-lg font-bold text-gray-900 mb-3">Explore Performance Areas</h2><div class="row g-4">@foreach($modules as $module)<div class="col-12 col-md-6 col-xl-3"><article class="card border-0 shadow-sm rounded-4 h-100"><div class="card-body p-4 d-flex flex-column"><span class="rounded-3 bg-{{ $module['tone'] }} bg-opacity-10 text-{{ $module['tone'] }} d-flex align-items-center justify-content-center mb-3" style="width:44px;height:44px"><i class="bi bi-{{ $module['icon'] }} fs-5"></i></span><h3 class="fs-5 fw-bold">{{ $module['title'] }}</h3><p class="small text-muted">{{ $module['description'] }}</p><dl class="small mb-4">@foreach($module['metrics'] as [$label,$value])<div class="d-flex justify-content-between gap-2 border-bottom py-2"><dt class="text-muted fw-normal">{{ $label }}</dt><dd class="fw-semibold mb-0 text-end">{{ $value }}</dd></div>@endforeach</dl><a href="{{ route($module['route']) }}" class="btn btn-sm btn-outline-{{ $module['tone'] }} mt-auto">{{ $module['action'] }} <i class="bi bi-arrow-right ms-1"></i></a></div></article></div>@endforeach</div></section>

    <section class="mt-5" aria-label="Revenue and target overview"><div class="row g-4"><div class="col-12 col-xl-7"><x-dashboard-overview-chart :initial-data="$revenueTrend" chart-id="dashboardRevenueChart" kind="revenue" title="Revenue Trend Overview" description="Recent monthly revenue movement from the Sales Reports page." /><div class="d-flex justify-content-end mt-2"><a href="{{ route('forecasting.reports') }}" class="btn btn-sm btn-link text-decoration-none">View Full Report <i class="bi bi-arrow-right"></i></a></div></div><div class="col-12 col-xl-5"><x-dashboard-overview-chart :initial-data="$targetVsActualSummary" chart-id="dashboardTargetChart" kind="target" title="Target vs. Actual Overview" description="A compact comparison of planned and completed revenue." /><div class="d-flex justify-content-between align-items-center mt-2"><span class="badge text-bg-success">{{ $targetVsActualSummary['status'] }}</span><a href="{{ route('forecasting.performance') }}" class="btn btn-sm btn-link text-decoration-none">View Performance Details <i class="bi bi-arrow-right"></i></a></div></div></div></section>

    <section class="mt-5" aria-labelledby="forecast-summary-heading"><div class="card border-0 shadow-sm rounded-4"><div class="card-body p-4"><div class="d-flex flex-wrap justify-content-between align-items-start gap-3"><div><h2 id="forecast-summary-heading" class="fs-5 fw-bold mb-1">Sales Forecast Summary</h2><p class="small text-muted mb-0">Revenue is expected to increase during the next period based on recent sales trends.</p></div><a href="{{ route('forecasting.forecast') }}" class="btn btn-sm btn-outline-primary">View Full Forecast</a></div><div class="row g-3 mt-2">@foreach([['Latest Actual','₱'.number_format($forecastSummary['latestActual'])],['Next-Month Forecast','₱'.number_format($forecastSummary['nextMonthForecast'])],['Expected Growth','+'.number_format($forecastSummary['growthRate'],1).'%'],['Direction',$forecastSummary['direction']],['Confidence',$forecastSummary['confidence'].'%']] as [$label,$value])<div class="col-6 col-lg"><div class="bg-light rounded-3 p-3 h-100"><div class="small text-muted">{{ $label }}</div><div class="fw-bold mt-1">{{ $value }}</div></div></div>@endforeach</div></div></div></section>

    <section class="mt-5" aria-labelledby="top-performance-heading"><div class="d-flex justify-content-between align-items-end mb-3"><div><h2 id="top-performance-heading" class="text-lg font-bold text-gray-900 mb-1">Top Sales Performance</h2><p class="small text-muted mb-0">Leading contributors from the current sales report.</p></div><a href="{{ route('forecasting.reports') }}" class="btn btn-sm btn-link text-decoration-none">View More</a></div><div class="row g-4">@foreach([['Top Products',$topProducts,'box-seam'],['Top Regions',$topRegions,'geo-alt'],['Top Sales Representatives',$topRepresentatives,'people']] as [$title,$items,$icon])<div class="col-12 col-lg-4"><article class="card border-0 shadow-sm rounded-4 h-100"><div class="card-body p-4"><h3 class="fs-6 fw-bold mb-4"><i class="bi bi-{{ $icon }} text-primary me-2"></i>{{ $title }}</h3>@php($maxValue = max([1, ...array_column($items,'value')]))@forelse($items as $index => $item)<div class="mb-3"><div class="d-flex justify-content-between gap-3"><span class="fw-semibold"><span class="text-muted me-2">#{{ $index + 1 }}</span>{{ $item['name'] }}</span><span>₱{{ number_format($item['value']) }}</span></div><div class="progress mt-2" style="height:6px"><div class="progress-bar bg-primary" style="width:{{ ($item['value'] / $maxValue) * 100 }}%"></div></div></div>@empty<p class="small text-muted mb-0">No sales data matches the selected period.</p>@endforelse</div></article></div>@endforeach</div></section>

    <section class="mt-5" aria-labelledby="priority-dashboard-heading"><div class="d-flex justify-content-between align-items-end mb-3"><h2 id="priority-dashboard-heading" class="text-lg font-bold text-gray-900 mb-0">Priority Recommendations</h2><a href="{{ route('forecasting.recommendations') }}" class="btn btn-sm btn-link text-decoration-none">View All Recommendations</a></div><div class="row g-4">@foreach($priorityRecommendations as $recommendation)<div class="col-12 col-lg-4"><article class="card border-0 shadow-sm rounded-4 h-100"><div class="card-body p-4 border-start border-4 {{ $recommendation['priority'] === 'High' ? 'border-danger' : 'border-warning' }}"><div class="d-flex justify-content-between gap-2 mb-3"><span class="badge text-bg-light border text-dark">{{ $recommendation['category'] }}</span><x-recommendation-priority-badge :priority="$recommendation['priority']" /></div><h3 class="fs-6 fw-bold">{{ $recommendation['title'] }}</h3><p class="small text-muted mb-2">{{ $recommendation['insight'] }}</p><p class="small mb-0"><strong>Action:</strong> {{ $recommendation['action'] }}</p></div></article></div>@endforeach</div><p class="small text-muted mt-3 mb-0"><i class="bi bi-info-circle me-1"></i>Recommendations remain suggestions until reviewed by management.</p></section>

    <section class="mt-5" aria-labelledby="recent-insights-heading"><h2 id="recent-insights-heading" class="text-lg font-bold text-gray-900 mb-3">Recent Performance Insights</h2><div class="row g-3">@foreach($recentInsights as $insight)@php($style = match($insight['type']) {'success' => ['alert-success','bi-check-circle-fill'], 'warning' => ['alert-warning','bi-exclamation-triangle-fill'], 'risk' => ['alert-danger','bi-shield-exclamation'], default => ['alert-info','bi-info-circle-fill']})<div class="col-12 col-md-6"><div class="alert {{ $style[0] }} h-100 mb-0 d-flex gap-3"><i class="bi {{ $style[1] }}"></i><span>{{ $insight['text'] }}</span></div></div>@endforeach</div></section>

    <section class="mt-5" aria-labelledby="quick-actions-heading"><h2 id="quick-actions-heading" class="text-lg font-bold text-gray-900 mb-3">Quick Actions</h2><div class="d-flex flex-wrap gap-2"><a href="{{ route('forecasting.reports') }}" class="btn btn-primary"><i class="bi bi-file-earmark-bar-graph me-2"></i>Generate Sales Report</a><a href="{{ route('forecasting.performance') }}" class="btn btn-outline-primary">View Target Performance</a><a href="{{ route('forecasting.forecast') }}" class="btn btn-outline-primary">Review Forecast</a><a href="{{ route('forecasting.recommendations') }}" class="btn btn-outline-primary">Open Recommendations</a><a href="{{ route('forecasting.export', ['type'=>'dashboard','format'=>'csv']) }}" class="btn btn-outline-secondary"><i class="bi bi-download me-2"></i>Export Dashboard Summary</a><a href="{{ route('forecasting.export', ['type'=>'dashboard','format'=>'print']) }}" target="_blank" class="btn btn-outline-secondary"><i class="bi bi-printer me-2"></i>Print / PDF</a></div></section>

    <aside class="alert alert-info mt-5 mb-4"><h2 class="fs-6 fw-bold"><i class="bi bi-info-circle me-2"></i>Dashboard data and methodology</h2><p class="mb-0">This dashboard summarizes sales-order records, target performance, calculated forecast trends, and business recommendations from the shared ERP database. When no qualifying sales records exist for the selected year, safe sample values keep the interface available. Forecasts and recommendations support management decisions and should be reviewed before actions are implemented.</p></aside>
@endsection
