<div id="rec-filter-overlay" class="rec-overlay" aria-hidden="true"><aside id="rec-filter-drawer" class="rec-drawer" role="dialog" aria-modal="true" aria-labelledby="rec-filter-title"><header class="d-flex gap-3 align-items-start p-4 border-bottom"><i class="bi bi-funnel fs-4 text-primary"></i><div class="flex-grow-1"><h2 id="rec-filter-title" class="fs-5 fw-bold mb-1">Recommendation Filters</h2><p class="small text-muted mb-0">Narrow the review queue by business context.</p></div><button id="rec-close-filter" type="button" class="btn-close" aria-label="Close recommendation filters"></button></header><div class="p-4 overflow-auto">
    @foreach(['period' => ['Date Range or Year',['Current Year','Previous Year','Current Quarter','Custom Range']], 'category' => ['Recommendation Category',['All Categories','Sales Strategy','Inventory Planning','Marketing','Regional Performance','Representative Performance','Target Adjustment']], 'priority' => ['Priority',['All Priorities','High','Medium','Low']], 'status' => ['Recommendation Status',['All Statuses','New','Under Review','Approved','In Progress','Completed','Dismissed']]] as $id => [$label,$options])<div class="mb-3"><label for="rec-{{ $id }}" class="form-label small fw-semibold">{{ $label }}</label><select id="rec-{{ $id }}" name="{{ $id }}" class="form-select">@foreach($options as $option)@php($value = \Illuminate\Support\Str::slug($option))<option value="{{ $value }}" @selected(request($id) === $value)>{{ $option }}</option>@endforeach</select></div>@endforeach
    <div class="mb-3"><label for="rec-product" class="form-label small fw-semibold">Product</label><select id="rec-product" name="product" class="form-select"><option value="all">All products</option>@foreach(($filterOptions['products'] ?? []) as $product)<option value="{{ $product->product_id }}" @selected((string) request('product') === (string) $product->product_id)>{{ $product->product_name }}</option>@endforeach</select></div>
    <div class="mb-3"><label for="rec-region" class="form-label small fw-semibold">Region</label><select id="rec-region" name="region" class="form-select"><option value="all">All regions</option>@foreach(($filterOptions['regions'] ?? []) as $region)<option value="{{ $region->region_id }}" @selected((string) request('region') === (string) $region->region_id)>{{ $region->region_name }}</option>@endforeach</select></div>
    <div class="mb-3"><label for="rec-representative" class="form-label small fw-semibold">Sales Representative</label><select id="rec-representative" name="representative" class="form-select"><option value="all">All representatives</option>@foreach(($filterOptions['representatives'] ?? []) as $representative)<option value="{{ $representative->employee_id }}" @selected((string) request('representative') === (string) $representative->employee_id)>{{ $representative->full_name }}</option>@endforeach</select></div>
    <div class="d-flex justify-content-end gap-2 mt-4"><button id="rec-reset" type="button" class="btn btn-outline-secondary">Reset</button><button id="rec-apply" type="button" class="btn btn-primary">Apply Filters</button></div>
</div></aside></div>
<style>.rec-overlay{position:fixed;inset:0;z-index:1050;background:rgba(15,23,42,.45);display:flex;justify-content:flex-end;opacity:0;pointer-events:none;transition:opacity .3s}.rec-overlay.open{opacity:1;pointer-events:auto}.rec-drawer{width:min(440px,calc(100vw - 24px));height:calc(100vh - 32px);margin:16px;background:#fff;border-radius:18px;box-shadow:0 18px 45px rgba(0,0,0,.22);transform:translateX(110%);transition:transform .38s cubic-bezier(.22,1,.36,1);overflow:hidden;display:flex;flex-direction:column}.rec-overlay.open .rec-drawer{transform:translateX(0)}</style>
<script src="{{ asset('js/recommendation-filter.js') }}"></script>
